[package]
name = "gaia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
base64 = ["dep:base64"]

[dependencies]
tink-core = { version = "0.2.5", features = ["insecure"] }
tink-streaming-aead = "0.2.5"
base64 = { version = "0.21.4", optional = true }